field.widget.settings.geojsonfile_widget:
  type: mapping
  label: 'Geojsonfile Widget settings'
  mapping:
    progress_indicator:
      type: string
      label: 'Progess indicator'
    file_directory:
      type: string
      label: 'File directory'
    max_filesize:
      type: string
      label: 'Max file size'


field.field_settings.geojsonfile_field:
  type: mapping
  label: 'Geojsonfile Widget settings'
  mapping:
    progress_indicator:
      type: string
      label: 'Progess indicator'
    file_directory:
      type: string
      label: 'File directory'
    max_filesize:
      type: string
      label: 'Max file size'
    color:
      type: string
      label: 'color'